### ISSUE TITLE
S3 Access Denied

### ISSUE THREAD

**Issue by etaty** [dwhjames/aws-wrap#39]
Hey Daniel, hope you are well

When requesting a non existing file ...
```scala
client.getObject(bucketname, "wtf.txt")
```

```
[error] Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: [removed]), S3 Extended Request ID: [removed]
[error] 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
[error] 	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
[error] 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
[error] 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
[error] 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3595)
[error] 	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1116)
[error] 	at com.github.dwhjames.awswrap.s3.AmazonS3ScalaClient$$anonfun$getObject$1.apply(s3.scala:382)
[error] 	at com.github.dwhjames.awswrap.s3.AmazonS3ScalaClient$$anonfun$getObject$1.apply(s3.scala:382)
[error] 	at com.github.dwhjames.awswrap.s3.AmazonS3ScalaClient$$anon$1$$anonfun$run$1.apply(s3.scala:207)
[error] 	at scala.util.Try$.apply(Try.scala:192)
[error] 	at com.github.dwhjames.awswrap.s3.AmazonS3ScalaClient$$anon$1.run(s3.scala:206)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

It is annoying as the main thread is stuck waiting for this thread. As if the exception is not catched at all

**Comment by etaty** [comment]
I am thinking about UncaughtExceptionHandler https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/impl/ExecutionContextImpl.scala#L51
You don't seem to set one

**Comment by dwhjames** [comment]
Hey @etaty,

I’ve been puzzling over this and I can’t see how this could be an uncaught exception in the thread pool:

```scala
  private def wrapMethod[Request, Result](
    f:       Request => Result,
    request: Request
  ): Future[Result] = {
    val p = Promise[Result]
    executorService.execute(new Runnable {
      override def run(): Unit = {
        p complete {
          Try {
            f(request)
          }
        }
        ()
      }
    })
    p.future
  }
```

The `AmazonS3Exception` is captured in `Try.apply`, and then the promise is completed with this failed Try. So the stacktrace looks as I would expect for this execution.

Also your stacktrace says the thread name is `"main"`, so this surely can’t be an uncaught exception in the thread pool for this reason as well.


Could you post some more context for your program? Maybe a minimal failing example? I’m currently inclined to think that the exception from the failed future is being extracted and thrown on your main thread.


As a general comment, I would suggest making use of the S3 TransferManager rather than direct calls to `get/putObject`, but I’d still like to get to the bottom of your issue here.

**Comment by etaty** [comment]
I am not using the TransferManager because i would like to get a Stream back and not a file.
Yeah I will give you a minimal project asap.

**Comment by dwhjames** [comment]
> I am not using the TransferManager because i would like to get a Stream back and not a file.

I guess you are ingesting it into some Scala streaming library?

**Comment by etaty** [comment]
yes scala stream, they are small csv file.

**Comment by etaty** [comment]
Okay I got confused by the the program not terminating (I needed to shutdown the client and transfermanager)
sorry

**Comment by dwhjames** [comment]
No worries. Yes, you need to manage the lifecycle of the thread resources.

You are free to supply your own thread factory and use daemon threads, just be careful :)
